input_path: /homes/abrace/data/bba/BBA-subset-100.h5
output_path: /homes/abrace/src/mdlearn/runs/test-run-0 
input_shape:
- 1
- 28
- 28
dataset_name: contact_map
scalar_dset_names: []
values_dset_name: null
scalar_requires_grad: false
in_memory: true
split_pct: 0.8
seed: 333
shuffle: true
epochs: 20
batch_size: 64
clip_grad_max_norm: 5.0
init_weights: null
optimizer:
    name: Adam
    hparams:
        lr: 0.0001
scheduler: null
latent_dim: 10
filters:
- 100
- 100
- 100
- 100
kernels:
- 5
- 5
- 5
- 5
strides:
- 1
- 2
- 1
- 1
affine_widths:
- 64
affine_dropouts:
- 0.0
activation: ReLU
output_activation: Sigmoid
lambda_rec: 1.0
num_data_workers: 0
ignore_gpu: false
